services:
  postgres:
    image: postgres:latest
    container_name: db-auth-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    volumes:
      - .docker/data/postgres_data:/var/lib/postgresql/data
      - .docker/data/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
