### GET user by id
GET {{base_url}}/users/1

### POST create user
POST {{base_url}}/users
Content-Type: application/json

{
  "name": "beltrano",
  "email": "beltrano@example.com",
  "password": "beltrano123"
}